name: llm-randomness-eval
channels:
  - pytorch
  - anaconda
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda
  - transformers
  - ray-default
  - pip:
    - vllm
    - llmcompressor
    - huggingface_hub[cli]
